### ISSUE TITLE
Package is very out of date

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/nbdev-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Out of date

### Installed packages

```shell
Update
```

### Environment info

```shell
NA
```

**Comment by thewchan** [comment]
@corneliusroemer looks like I inadvertently neglected this one, apologies. Let me ping the bot to grab the newest version

**Comment by corneliusroemer** [comment]
No worries! thanks for quick response!

**Comment by jph00** [comment]
Is there any way to set this up so the conda-forge package is automatically kept up to date? We keep the official version on our own fastai channel, and it can cause confusion when the conda-forge version is different.

**Comment by corneliusroemer** [comment]
PRs should be made automatically when you publish to Pypi, however manual review is always required I think.

You could add someone from the maintainers to the feedstock to increase resilience and reduce time to update.

**Comment by corneliusroemer** [comment]
See https://conda-forge.org/docs/maintainer/updating_pkgs/
